name: 'Create Issue Github Action (Testing)'
description: 'Create a issue in github'
author: 'Shimul Kumar Saha'

# Define your inputs here.
inputs:
  token:
    description: 'Token to use for creating issues'
    required: true
  title:
    description: 'Title of the issue'
    required: true
  body:
    description: 'Body of the issue'
    required: true
  assignees:
    description: 'Assignees of the issues in newline separated'    

# Define your outputs here.
outputs:
  issue:
    description: 'The issue in json format'

runs:
  using: node20
  main: dist/index.js
  
