name: Publish a Release
on:
  release:
    types: [published, edited]

jobs:
  publish-release:
    runs-on: ubuntu
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
